name: eventz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animations: ^2.0.0
  awesome_flutter_widgets:
    git:
      url: https://github.com/ShubheshDixit/awesome_flutter_widgets.git
  barcode_widget: ^2.0.1
  cached_network_image: ^3.0.0
  carousel_slider: ^3.0.0
  cloud_firestore: ^1.0.3
  cupertino_icons: ^1.0.1
  dio: ^4.0.0
  dotted_border: ^2.0.0
  fancy_shimmer_image: ^2.0.0+1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_dynamic_links: ^2.0.0
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.0.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^8.1.1+2
  flutter_spinkit: ^5.0.0
  flutter_swiper: ^1.1.6
  flutter_web_plugins:
    sdk: flutter
  flutter_webview_plugin: ^0.4.0
  font_awesome_flutter: ^8.11.0
  google_fonts: ^2.0.0
  html_unescape: ^2.0.0
  http: ^0.13.3
  intl: ^0.17.0
  intro_views_flutter: ^3.0.0
  jiffy: ^4.1.0
  latlng: ^0.1.0
  map: ^1.0.0
  map_launcher: ^2.0.0
  markdown_widget: any
  permission_handler: ^7.0.0
  routemaster: ^0.9.3
  shimmer: ^2.0.0
  simple_animations: ^3.0.3
  simple_gesture_detector: ^0.2.0
  stripe: ^4.4.0
  stripe_payment: ^1.1.1
  table_calendar: ^3.0.0
  theme_mode_handler: ^2.0.0
  url_launcher: ^6.0.3
  uuid: ^3.0.2
  video_player: ^2.1.1
  webview_flutter: ^2.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icons/icon_blue.jpg"

flutter:
  uses-material-design: true

  assets:
    - images/posters/
    - images/illustrations/
    - images/mock/
    - audio/
