name: eventz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_flutter_widgets:
    git:
      url: https://github.com/ShubheshDixit/awesome_flutter_widgets.git
  animated_icon_button: ^0.4.1
  animations: ^1.1.2
  barcode_widget: ^1.5.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.3
  cupertino_icons: ^1.0.1
  dotted_border: ^1.0.7
  file_picker: null
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_dynamic_links: ^0.8.0
  firebase_messaging: ^9.1.0
  firebase_storage: ^8.0.1
  flutter_spinkit: ^5.0.0
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.11.0
  google_fonts: ^2.0.0
  intl: null
  intro_views_flutter: ^2.8.2
  jiffy: null
  latlng: null
  map: null
  permission_handler: ^6.1.1
  simple_animations: ^2.5.1
  simple_gesture_detector: ^0.1.6
  table_calendar: ^2.3.3
  uuid: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/posters/
    - images/illustrations/
    - images/illustrations/pink/
    - fonts/
    - audio/

  fonts:
    - family: Bam
      fonts:
        - asset: fonts/Bing Bam Boum.ttf

    - family: Meg
      fonts:
        - asset: fonts/MEGAMIND-PersonalUse.otf

    - family: Emate
      fonts:
        - asset: fonts/EMATANE-PersonalUse.otf

    - family: Grobold
      fonts:
        - asset: fonts/GROBOLD.ttf
